Repository Azure/arc_jumpstart_docs, pull requests merged in 2024-08, with the labels that each got.

#346 ArcBox 3.0 - Updated deployment options and prerequisites
  docs/azure_jumpstart_arcbox/DataOps/_index.md
  docs/azure_jumpstart_arcbox/DataOps/parameters_dataops_bicep.png
  docs/azure_jumpstart_arcbox/DevOps/_index.md
  docs/azure_jumpstart_arcbox/DevOps/parameters_devops_bicep.png
  docs/azure_jumpstart_arcbox/ITPro/_index.md
  docs/azure_jumpstart_arcbox/ITPro/parameters_bicep.png
  docs/azure_jumpstart_arcbox/ITPro/parameters_itpro_bicep.png
Labels: documentation, review

#351 ArcBox 3.0 - Added section on Azure Update Manager
  docs/azure_jumpstart_arcbox/ITPro/_index.md
  docs/azure_jumpstart_arcbox/ITPro/azure-update-manager-1.png
  docs/azure_jumpstart_arcbox/ITPro/azure-update-manager-2.png
Labels: documentation

#359 ArcBox 3.0 - update to SSH section
  docs/azure_jumpstart_arcbox/ITPro/_index.md
  docs/azure_jumpstart_arcbox/ITPro/ssh_via_az_cli_01.png
  docs/azure_jumpstart_arcbox/ITPro/ssh_via_az_ps_01.png
Labels: documentation

#361 ArcBox 3.0 - SQL Server migration assessment documentation
  docs/azure_jumpstart_arcbox/DataOps/_index.md
  docs/azure_jumpstart_arcbox/DataOps/sql-server-migration-assessment.png
  docs/azure_jumpstart_arcbox/DataOps/sql-server-migration-overview.png
  docs/azure_jumpstart_arcbox/DataOps/sql-server-migration-readines-not-ready.png
  docs/azure_jumpstart_arcbox/DataOps/sql-server-migration-readines-ready.png
  docs/azure_jumpstart_arcbox/DataOps/sql-server-migration-readines.png
Labels: documentation, review

#365 ArcBox 3.0 - added autoshutdown-parameters and updated client VM SKU
  docs/azure_jumpstart_arcbox/ITPro/_index.md
  docs/azure_jumpstart_arcbox/ITPro/parameters_itpro_bicep.png
Labels: documentation

#376 Resolved DataOps documentation merge conflicts
  docs/azure_jumpstart_arcbox/DataOps/arcbox-datastudio-connections.png
  docs/azure_jumpstart_arcbox/DataOps/arcbox_complete.png
  docs/azure_jumpstart_arcbox/DataOps/arcbox_k3s_data_vm_ip.png
  docs/azure_jumpstart_arcbox/DataOps/arch_dataops.png
  docs/azure_jumpstart_arcbox/DataOps/bookstore04.png
  docs/azure_jumpstart_arcbox/DataOps/bookstore08.png
  docs/azure_jumpstart_arcbox/DataOps/bookstore12.png
  docs/azure_jumpstart_arcbox/DataOps/dataops-architecture.png
  docs/azure_jumpstart_arcbox/DataOps/dataops-progress.png
  docs/azure_jumpstart_arcbox/DataOps/deployed_resources.png
  docs/azure_jumpstart_arcbox/DataOps/deployment_flow_tf.png
  docs/azure_jumpstart_arcbox/DataOps/grafana_icon.png
  docs/azure_jumpstart_arcbox/DataOps/grafana_ip_address.png
  docs/azure_jumpstart_arcbox/DataOps/k3s_bookstore01.png
  docs/azure_jumpstart_arcbox/DataOps/k3s_bookstore02.png
  docs/azure_jumpstart_arcbox/DataOps/k3s_bookstore03.png
  docs/azure_jumpstart_arcbox/DataOps/k3s_bookstore04.png
  docs/azure_jumpstart_arcbox/DataOps/k3s_bookstore05.png
  docs/azure_jumpstart_arcbox/DataOps/k3s_bookstore06.png
  docs/azure_jumpstart_arcbox/DataOps/k3s_bookstore07.png
  docs/azure_jumpstart_arcbox/DataOps/k3s_bookstore08.png
  docs/azure_jumpstart_arcbox/DataOps/k3s_bookstore09.png
  docs/azure_jumpstart_arcbox/DataOps/k3s_bookstore10.png
  docs/azure_jumpstart_arcbox/DataOps/k3s_bookstore11.png
  docs/azure_jumpstart_arcbox/DataOps/k3s_bookstore12.png
  docs/azure_jumpstart_arcbox/DataOps/k3s_bookstore13.png
  docs/azure_jumpstart_arcbox/DataOps/k3s_bookstore14.png
  docs/azure_jumpstart_arcbox/DataOps/k3s_bookstore15.png
  docs/azure_jumpstart_arcbox/DataOps/portal_delete.png
  docs/azure_jumpstart_arcbox/DataOps/rdp_nsg_blocked.png
  docs/azure_jumpstart_arcbox/DataOps/sqlmi-endpoint_file.png
  docs/azure_jumpstart_arcbox/DataOps/sqlmi-pitr-azdatastudio-k3ssql.png
  docs/azure_jumpstart_arcbox/DataOps/sqlmi-pitr-connect-datacontroller-details.png
  docs/azure_jumpstart_arcbox/DataOps/sqlmi-pitr-connect-datacontroller-manage.png
  docs/azure_jumpstart_arcbox/DataOps/sqlmi-pitr-connect-to-sqlmi.png
  docs/azure_jumpstart_arcbox/DataOps/sqlmi-pitr-database-list.png
  docs/azure_jumpstart_arcbox/DataOps/sqlmi-pitr-database-select-restore.png
  docs/azure_jumpstart_arcbox/DataOps/sqlmi-pitr-datacontroller.png
  docs/azure_jumpstart_arcbox/DataOps/sqlmi-pitr-targetdb.png
  docs/azure_jumpstart_arcbox/DataOps/sqlmi_connection_portal.png
  docs/azure_jumpstart_arcbox/DataOps/ssms_aks_endpoints_file.png
  docs/azure_jumpstart_arcbox/DataOps/ssms_db_comparison.png
  docs/azure_jumpstart_arcbox/DataOps/ssms_db_restore_complete.png
  docs/azure_jumpstart_arcbox/DataOps/ssms_new_query.png
  docs/azure_jumpstart_arcbox/DataOps/troubleshoot_logs.png
Labels: documentation, needs author feedback
