Repository Azure/arc_jumpstart_docs, pull requests merged in 2024-01, with the labels that each got.

#197 Arc-enabled SQL Server scenario updates
  docs/azure_arc_jumpstart/azure_arc_sqlsrv/azure/azure_arm_template_sqlsrv_winsrv_defender/_index.md
  docs/azure_arc_jumpstart/azure_arc_sqlsrv/azure/azure_arm_template_sqlsrv_winsrv_defender/connect-guest-sql-vm.png
  docs/azure_arc_jumpstart/azure_arc_sqlsrv/azure/azure_arm_template_sqlsrv_winsrv_defender/defender-sql-testing-script.png
  docs/azure_arc_jumpstart/azure_arc_sqlsrv/azure/azure_arm_template_sqlsrv_winsrv_defender/execute-defender-simulation-script.png
  docs/azure_arc_jumpstart/azure_arc_sqlsrv/azure/azure_arm_template_sqlsrv_winsrv_defender/locate-guest-sql-vm.png
  docs/azure_arc_jumpstart/azure_arc_sqlsrv/azure/azure_arm_template_sqlsrv_winsrv_defender/locate-hyper-v-manager.png
  docs/azure_arc_jumpstart/azure_arc_sqlsrv/azure/azure_arm_template_sqlsrv_winsrv_defender/locate-simulation-script.png
  docs/azure_arc_jumpstart/azure_arc_sqlsrv/azure/azure_arm_template_sqlsrv_winsrv_defender/login-to-guest-vm.png
  docs/azure_arc_jumpstart/azure_arc_sqlsrv/azure/azure_arm_template_sqlsrv_winsrv_defender/manual-brute-force-test.png
  docs/azure_arc_jumpstart/azure_arc_sqlsrv/azure/azure_arm_template_sqlsrv_winsrv_defender/portaldeploy.png
Labels: documentation

#180 Vale integration for markdown formatting and styling
  .github/styles/Microsoft/AMPM.yml
  .github/styles/Microsoft/Accessibility.yml
  .github/styles/Microsoft/Acronyms.yml
  .github/styles/Microsoft/Adverbs.yml
  .github/styles/Microsoft/Auto.yml
  .github/styles/Microsoft/Avoid.yml
  .github/styles/Microsoft/ComplexWords.yml
  .github/styles/Microsoft/Contractions.yml
  .github/styles/Microsoft/Dashes.yml
  .github/styles/Microsoft/DateFormat.yml
  .github/styles/Microsoft/DateNumbers.yml
  .github/styles/Microsoft/DateOrder.yml
  .github/styles/Microsoft/Ellipses.yml
  .github/styles/Microsoft/FirstPerson.yml
  .github/styles/Microsoft/Foreign.yml
  .github/styles/Microsoft/Gender.yml
  .github/styles/Microsoft/GenderBias.yml
  .github/styles/Microsoft/GeneralURL.yml
  .github/styles/Microsoft/HeadingAcronyms.yml
  .github/styles/Microsoft/HeadingColons.yml
  .github/styles/Microsoft/HeadingPunctuation.yml
  .github/styles/Microsoft/Headings.yml
  .github/styles/Microsoft/Hyphens.yml
  .github/styles/Microsoft/Negative.yml
  .github/styles/Microsoft/Ordinal.yml
  .github/styles/Microsoft/OxfordComma.yml
  .github/styles/Microsoft/Passive.yml
  .github/styles/Microsoft/Percentages.yml
  .github/styles/Microsoft/Quotes.yml
  .github/styles/Microsoft/RangeFormat.yml
  .github/styles/Microsoft/RangeTime.yml
  .github/styles/Microsoft/Ranges.yml
  .github/styles/Microsoft/Semicolon.yml
  .github/styles/Microsoft/SentenceLength.yml
  .github/styles/Microsoft/Spacing.yml
  .github/styles/Microsoft/Suspended.yml
  .github/styles/Microsoft/Terms.yml
  .github/styles/Microsoft/URLFormat.yml
  .github/styles/Microsoft/Units.yml
  .github/styles/Microsoft/Vocab.yml
  .github/styles/Microsoft/We.yml
  .github/styles/Microsoft/Wordiness.yml
  .github/styles/Microsoft/meta.json
  .github/styles/Vocab/Jumpstart/accept.txt
  .github/styles/Vocab/Jumpstart/reject.txt
  .github/workflows/canary-pr-review.yml
  .vale.ini
  README.md
  SUPPORT.md
Labels: enhancement

#232 Missing images in jumpstart "Deploy AKS cluster on Azure IoT Edge and connect it to Azure Arc using Terraform"
  docs/azure_arc_jumpstart/azure_edge_iot_ops/aks_iot_edge_terraform/13.png
  docs/azure_arc_jumpstart/azure_edge_iot_ops/aks_iot_edge_terraform/15.png
  docs/azure_arc_jumpstart/azure_edge_iot_ops/aks_iot_edge_terraform/16.png
Labels: bug, documentation
