Repository Azure/arc_jumpstart_docs, pull requests merged in 2024-04, with the labels that each got.

#280 Added information about automatic deployment of the Azure Arc-enabled HCI cluster
  docs/azure_jumpstart_hcibox/cloud_deployment/_index.md
  docs/azure_jumpstart_hcibox/deployment_az/_index.md
  docs/azure_jumpstart_hcibox/getting_started/_index.md
Labels: enhancement

#282 Add autoUpgradeClusterResource option for automatic cluster upgrade
  docs/azure_jumpstart_hcibox/deployment_az/_index.md
  docs/azure_jumpstart_hcibox/using_hcibox/_index.md
  docs/azure_jumpstart_hcibox/using_hcibox/cluster_updates.png
Labels: enhancement

#283 Fix indentation in Azure CLI parameters
  docs/azure_jumpstart_hcibox/deployment_az/_index.md
Labels: documentation

#289 Updated 01.png, added not for supported locations, mentioned ESA is in public preview
  docs/azure_arc_jumpstart/azure_edge_iot_ops/aks_edge_essentials_single_esa/01.png
  docs/azure_arc_jumpstart/azure_edge_iot_ops/aks_edge_essentials_single_esa/_index.md
Labels: review
