Repository Azure/arc_jumpstart_docs, pull requests merged in 2024-05, with the labels that each got.

#308 First version of welding flow documentation
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/welding_defect/_index.md
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/welding_defect/img/flow.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/welding_defect/img/welding_ui.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/welding_monitoring/_index.md
Labels: documentation

#305 arc_monitoring_servers docs
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/arc_monitoring_servers/_index.md
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/arc_monitoring_servers/img/arcserverskubernetesclusters_inventoryworkbook.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/arc_monitoring_servers/img/azure_monitor_initiative.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/arc_monitoring_servers/img/click_inventoryworkbook.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/arc_monitoring_servers/img/click_osworkbook.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/arc_monitoring_servers/img/cpuusage_osworkbook.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/arc_monitoring_servers/img/dcr_datasources.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/arc_monitoring_servers/img/dcr_resources.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/arc_monitoring_servers/img/dcr_vmi.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/arc_monitoring_servers/img/defenderalerts_inventoryworkbook.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/arc_monitoring_servers/img/machinesoverall_inventoryworkbook.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/arc_monitoring_servers/img/open_inventoryworkbook.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/arc_monitoring_servers/img/open_osworkbook.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/arc_monitoring_servers/img/search_arc_server.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/arc_monitoring_servers/img/search_dcr.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/arc_monitoring_servers/img/search_policy.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/arc_monitoring_servers/img/search_workbooks.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/arc_monitoring_servers/img/summarize_osworkbook.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/arc_monitoring_servers/img/updatesdata_inventoryworkbook.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/arc_monitoring_servers/img/vminsights_map.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/arc_monitoring_servers/img/vminsights_performance.png
Labels: documentation, review

#309 ag_mfg troubleshooting, faq, cleanup
  docs/azure_jumpstart_ag/faq/_index.md
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/_index.md
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/electricity_forecasting/_index.md
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/troubleshooting/_index.md
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/troubleshooting/aad_quota_exceeded.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/troubleshooting/adx_switch.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/troubleshooting/adx_trouble.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/troubleshooting/az_vm_list_usage.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/troubleshooting/logs_folder.png
Labels: review

#306 AI Inferencing flow (OVMS and WebUI)
  .github/styles/Microsoft/AMPM.yml
  .github/styles/Microsoft/Accessibility.yml
  .github/styles/Microsoft/Acronyms.yml
  .github/styles/Microsoft/Adverbs.yml
  .github/styles/Microsoft/Auto.yml
  .github/styles/Microsoft/Avoid.yml
  .github/styles/Microsoft/ComplexWords.yml
  .github/styles/Microsoft/Contractions.yml
  .github/styles/Microsoft/Dashes.yml
  .github/styles/Microsoft/DateFormat.yml
  .github/styles/Microsoft/DateNumbers.yml
  .github/styles/Microsoft/DateOrder.yml
  .github/styles/Microsoft/Ellipses.yml
  .github/styles/Microsoft/FirstPerson.yml
  .github/styles/Microsoft/Foreign.yml
  .github/styles/Microsoft/Gender.yml
  .github/styles/Microsoft/GenderBias.yml
  .github/styles/Microsoft/GeneralURL.yml
  .github/styles/Microsoft/HeadingAcronyms.yml
  .github/styles/Microsoft/HeadingColons.yml
  .github/styles/Microsoft/HeadingPunctuation.yml
  .github/styles/Microsoft/Headings.yml
  .github/styles/Microsoft/Hyphens.yml
  .github/styles/Microsoft/Negative.yml
  .github/styles/Microsoft/Ordinal.yml
  .github/styles/Microsoft/OxfordComma.yml
  .github/styles/Microsoft/Passive.yml
  .github/styles/Microsoft/Percentages.yml
  .github/styles/Microsoft/Quotes.yml
  .github/styles/Microsoft/RangeFormat.yml
  .github/styles/Microsoft/RangeTime.yml
  .github/styles/Microsoft/Ranges.yml
  .github/styles/Microsoft/Semicolon.yml
  .github/styles/Microsoft/SentenceLength.yml
  .github/styles/Microsoft/Spacing.yml
  .github/styles/Microsoft/Suspended.yml
  .github/styles/Microsoft/Terms.yml
  .github/styles/Microsoft/URLFormat.yml
  .github/styles/Microsoft/Units.yml
  .github/styles/Microsoft/Vocab.yml
  .github/styles/Microsoft/We.yml
  .github/styles/Microsoft/Wordiness.yml
  .github/styles/Microsoft/meta.json
  .github/workflows/canary-pr-review.yml
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/ai_inferencing/_index.md
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/ai_inferencing/img/ai_flow.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/ai_inferencing/img/ovms.png
Labels: documentation, review

#304 Agora manufacturing data pipeline README
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/data_opc/_index.md
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/data_opc/img/adx_confirm_dashboard_report_name.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/data_opc/img/adx_contoso_motors_production_metrics.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/data_opc/img/adx_contoso_motors_report_select_timerange.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/data_opc/img/adx_contoso_motors_with_simulated_data.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/data_opc/img/adx_contoso_motors_with_simulated_data_selected_timerange.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/data_opc/img/adx_dashboard_report_files.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/data_opc/img/adx_import_dashboard_file.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/data_opc/img/adx_manufacturing_report_empty_data.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/data_opc/img/adx_select_dashboard_file.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/data_opc/img/adx_view_dashboards.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/data_opc/img/confirm_sample_data_generation.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/data_opc/img/confirm_sample_data_past_days.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/data_opc/img/contoso_motors-datapipeline_architecture.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/data_opc/img/locate_data_emulator_desktop.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/data_opc/img/sample_data_generation.png
Labels: documentation, needs author feedback

#320 Updated data pipeline images after the report name fixes
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/data_opc/img/adx_contoso_motors_production_metrics.png
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/data_opc/img/adx_manufacturing_report_empty_data.png
Labels: documentation

#321 Adding FAQ for Jumpstart Drops
  docs/FAQ/_index.md
Labels: documentation, needs author feedback, review

#325 Update technology stack for Welding/Safety/Architecture
  docs/azure_jumpstart_ag/manufacturing/contoso_motors/_index.md
Labels: review

#328 Drops contibution guidelines
  .github/styles/Vocab/Jumpstart/accept.txt
  .gitignore
  docs/drops_contribution_guidelines/_index.md
  docs/drops_contribution_guidelines/checks.png
  docs/drops_contribution_guidelines/contribution_flow.png
  docs/drops_contribution_guidelines/drop_definition.png
  docs/drops_contribution_guidelines/drop_submission.png
  docs/drops_contribution_guidelines/folder_structure.png
  docs/drops_contribution_guidelines/preview_site.png
  docs/drops_contribution_guidelines/right_bar.png
  docs/drops_contribution_guidelines/right_bar_example.png
Labels: documentation, review
