Repository Azure/arc_jumpstart_docs, pull requests merged in 2024-03, with the labels that each got.

#266 Include note in the HCI AZD deployment to highlight different context between PowerShell and AZD CLI
  docs/azure_jumpstart_hcibox/deployment_azd/_index.md
Labels: review

#271 run command new commit
  .gitignore
  docs/azure_arc_jumpstart/azure_arc_servers/day2/arc_run_command/01.png
  docs/azure_arc_jumpstart/azure_arc_servers/day2/arc_run_command/02.png
  docs/azure_arc_jumpstart/azure_arc_servers/day2/arc_run_command/03.png
  docs/azure_arc_jumpstart/azure_arc_servers/day2/arc_run_command/04.png
  docs/azure_arc_jumpstart/azure_arc_servers/day2/arc_run_command/05.png
  docs/azure_arc_jumpstart/azure_arc_servers/day2/arc_run_command/06.png
  docs/azure_arc_jumpstart/azure_arc_servers/day2/arc_run_command/_index.md
Labels: enhancement, review

#272 Fixed screenshots and changed "RUN" to "Run" in title
  .gitignore
  docs/azure_arc_jumpstart/azure_arc_servers/day2/arc_run_command/05.png
  docs/azure_arc_jumpstart/azure_arc_servers/day2/arc_run_command/_index.md
Labels: bug
